Survey
Azure/azure-powershell-common pull request #336
Opened 2022-08-20 10:16 UTC by Nickcandy

[Update az prompted survey mechanism](https://github.com/Azure/azure-powershell-common/commit/74315e94d457e8eb8da918a66135347c68977fa8)

2022-08-26 03:06 UTC, isra-fel requested changes
- The installation ID is not strongly tied to survey or telemetry, so I recommend extracting it to a `Share/InstallationHelper.cs`.
- Have you tested the compatibility of new code + old AzureRmSurvey.json?

2022-08-26 03:06 UTC, isra-fel commented on src/Share/Survey/SurveyHelper.cs
> +        private void InitialSurveyHelper(){
Our coding style is to put { in a standalone line. Please remember to format the document after making any changes
```suggestion
        private void InitialSurveyHelper()
        {
```

2022-08-26 12:09 UTC, dingmeng-xue commented on src/Common/MetricHelper.cs
> +    public String InstallationId {get; set;}
Is it required?

2022-08-26 12:09 UTC, dingmeng-xue commented on src/Common/AzurePSCmdlet.cs
> +            _qosEvent.InstallationId = InstallationId;
Given _qosEvent should have installation at beginning. Why is it set again?

2022-08-26 12:15 UTC, dingmeng-xue commented on src/Share/Survey/SurveyHelper.cs
> +        public bool ShouldPropmtAzSurvey(String installationId){
Do you need `installationId` to determine survey should be prompt or not? If no, this parameter should be removed.

2022-08-30 08:15 UTC, dingmeng-xue commented on src/Common/AzurePSCmdlet.cs
> +        private static string ansiCodePrefix = "\u001b[97;48;2;0;120;212m";
Please add comment

2022-08-30 08:17 UTC, dingmeng-xue commented on src/Common/AzurePSCmdlet.cs
> +                    && !configManager.GetConfigValue<bool>(ConfigKeysForCommon.EnableInterceptSurvey).Equals(false)))
Please correct this line.

2022-08-30 08:19 UTC, dingmeng-xue commented on src/Common/MetricHelper.cs
> +        public static string InstallationId { get => AzureSession.Instance.ExtendedProperties.TryGetValue("InstallationId", out String InstallationId)?InstallationId:""; }
String.Empty

2022-09-01 03:38 UTC, closed without merging