Enable TenantId to Retrieve Auxiliary Auth Header
Azure/azure-powershell-common pull request #409
Opened 2024-01-11 09:52 UTC by msJinLei

2024-01-18 07:12 UTC, isra-fel requested changes

2024-01-18 07:12 UTC, isra-fel commented on src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs
> +        protected IDictionary<string, List<string>> GetAuxiliaryAuthHeaderFromTenantIds(IEnumerable<string> tenantIds)
IList?

2024-01-18 07:12 UTC, isra-fel commented on src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs
> +                    throw new ArgumentException("Number of tenants (tenants other than the one in the current context), that the requested resources belongs to, exceeds maximum allowed number of " +
```suggestion
                    throw new ArgumentException("Number of tenants (tenants other than the one in the current context), that the requested resources belong to, exceeds maximum allowed number of " + MAX_NUMBER_OF_TOKENS_ALLOWED_IN_AUX_HEADER);
```

2024-01-18 07:43 UTC, wyunchi-ms commented on src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs
> +                var tokens = tenantIds.Select(t => (new StringBuilder(AUX_TOKEN_PREFIX).Append(" ").Append(GetTokenForTenant(t)?.AccessToken))?.ToString())?.ConcatStrings(AUX_TOKEN_APPEND_CHAR);
```suggestion
var tokens = tenantIds
    .Select(t => $"{AUX_TOKEN_PREFIX} {GetTokenForTenant(t)?.AccessToken}")
    .ConcatStrings(AUX_TOKEN_APPEND_CHAR);
```

2024-01-22 06:50 UTC, isra-fel approved these changes
Please provide context in PR descrption. You can leverage the AIG draft BTW

2024-01-22 06:50 UTC, wyunchi-ms approved these changes

2024-01-22 07:22 UTC, wyunchi-ms approved these changes

2024-01-22 09:42 UTC, isra-fel approved these changes

2024-01-22 09:42 UTC, merged